tbl <- read.table("Cimmitis_RS_Genome.rpt.bedtools.tab",header=F,sep="\t")
len <- abs(tbl$V3-tbl$V2)
tbl$V9 <- (tbl$V7 / len)
tbl$V10 <- (tbl$V8 / len)
colnames(tbl) <- c("Scaffold","ChrStart","ChrEnd","TE_name_instance","RepeatMasker Score","Strand","Hyphae Expression", "Spherule Expression","Hyphae Expression Normalized","Spherule Expression Normalized")
write.csv(tbl,file="Cimmitis_RS_Genome.rpt.bedtools.csv")
